---
version: "2.0"
services:
  softether:
    image: andrey01/softether:4.38-9760-2
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 992
        as: 992
        to:
          - global: true
      - port: 5555
        as: 5555
        to:
          - global: true
      - port: 1194
        as: 1194
        proto: udp
        to:
          - global: true
      - port: 500
        as: 500
        proto: udp
        to:
          - global: true
      - port: 4500
        as: 4500
        proto: udp
        to:
          - global: true
  app:
    image: declab/v2ray:0.2
    env:
      - "ID=7142a3f6-5788-4c91-839a-25b06fe58f4b"
    expose:
      - port: 1010
        as: 1010
        to:
          - global: true
      - port: 1080
        as: 1080
        to:
          - global: true
profiles:
  compute:
    softether:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    app:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    dcloud:
      pricing:
        softether:f
          denom: uakt
          amount: 100000
        app:
          denom: uakt
          amount: 100000
deployment:
  softether:
    dcloud:
      profile: softether
      count: 1
  app:
    dcloud:
      profile: app
      count: 1