---
version: "2.0"

services:
  web:
    image: elliothudsondev/akash-vpn:0.0.4
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - PORT=3000

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi

  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 10000

deployment:
  web:
    dcloud:
      profile: web
      count: 1