version: 2.0

services:
  docs:
    image: rodrirr/akashvpn-docs:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    docs-profile:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 512Mi
  placement:
    akash:
      pricing:
        docs-profile:
          denom: uakt
          amount: 5000

deployment:
  docs:
    akash:
      profile: docs-profile
      count: 1
